# Generated by Django 4.1.7 on 2023-04-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, default='usuario/user.png', null=True, upload_to='usuario'),
        ),
    ]
