# Generated by Django 4.1.7 on 2023-04-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data',
            field=models.DateField(default='15/04/2023'),
        ),
    ]
