# Generated by Django 4.1.7 on 2023-04-18 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produtos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 17, 22, 35, 56, 214713)),
        ),
    ]
