# Generated by Django 4.1.7 on 2023-04-19 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produtos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 21, 19, 1, 135159)),
        ),
    ]
