# Generated by Django 4.1.7 on 2023-04-19 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_produtos_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='codigo',
            field=models.CharField(default='5F6DIV', max_length=6),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 21, 22, 23, 570977)),
        ),
    ]
